---
application_name: Leanflow Pro
business_name: Leanflow Pro, LLC
business_address: 
domain: leanflowpro.com
support_email: support@leanflowpro.com
default_from_email: Leanflow Pro <no-reply@leanflowpro.com>
background_job_processor: solid_queue
email_provider: sendgrid
personal_accounts: false
apns: true
fcm: true
integrations:
- sentry
omniauth_providers:
payment_processors:
- stripe
multitenancy:
- path
gems:
- acts_as_tenant
- refer
- whenever
